// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVPY003tbihZ8S74C03sLH2f3-8UFVFS4',
    appId: '1:104650045238:web:25f6e944c3ab93dcc9a597',
    messagingSenderId: '104650045238',
    projectId: 'digital-twin-g7-project',
    authDomain: 'digital-twin-g7-project.firebaseapp.com',
    storageBucket: 'digital-twin-g7-project.firebasestorage.app',
    measurementId: 'G-J9V3YCK0NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVvnlxp08Qmrou_dc9kSLagEdGY8bEr4',
    appId: '1:104650045238:android:c51c5cd40ec2557dc9a597',
    messagingSenderId: '104650045238',
    projectId: 'digital-twin-g7-project',
    storageBucket: 'digital-twin-g7-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOeftnxq60OfXLLE-zEEr_DtV-FzAFGag',
    appId: '1:104650045238:ios:d8d2a55fe3af61cac9a597',
    messagingSenderId: '104650045238',
    projectId: 'digital-twin-g7-project',
    storageBucket: 'digital-twin-g7-project.firebasestorage.app',
    iosBundleId: 'com.example.evDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOeftnxq60OfXLLE-zEEr_DtV-FzAFGag',
    appId: '1:104650045238:ios:d8d2a55fe3af61cac9a597',
    messagingSenderId: '104650045238',
    projectId: 'digital-twin-g7-project',
    storageBucket: 'digital-twin-g7-project.firebasestorage.app',
    iosBundleId: 'com.example.evDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVPY003tbihZ8S74C03sLH2f3-8UFVFS4',
    appId: '1:104650045238:web:1f9efc831817930bc9a597',
    messagingSenderId: '104650045238',
    projectId: 'digital-twin-g7-project',
    authDomain: 'digital-twin-g7-project.firebaseapp.com',
    storageBucket: 'digital-twin-g7-project.firebasestorage.app',
    measurementId: 'G-MZZ1GMH84X',
  );
}
